# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emerywebster.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Webb Henderson
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Person website of Webb Henderson" # used by search engines

  # Header and footer text
  header_text:
#     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
#     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
   This website is <a href="https://github.com/emerywebster/emerywebster.github.io">open source</a>.<br /
   &copy; 2015 : <a href="https://github.com/emerywebster/emerywebster.github.io/blob/master/LICENSE.md">License</a> : Hosted by <a href="https://pages.github.com/">GitHub Pages</a>.

  # Icons
  rss: false
  github: "emerywebster"
  linkedin:  "http://www.linkedin.com/in/emerywebster"
  twitter: "emerywebster"
  instagram: "emerywebster"
  email_address: # Full email address, e.g. "sam@example.com"

  # Scripts
  google_analytics: "UA-8462524-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Older"
  str_prev: "Newer"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "footnotes"]
sass:
  sass_dir: _sass
  style: :compressed
highlighter: pygments
permalink: /:year/:month/:day/:title/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

