# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "/"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Webb Henderson

# Short description of your site
description: Personal website of Webb Henderson

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About: "about"
  Archive: "archive"
#    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
#    - Learn markdown: "http://www.markdowntutorial.com/"
#    - GitHub Pages: "https://pages.github.com/"
  Portfolio: "http://ux.emerywebster.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: /img/avatar.jpg

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Webb Henderson
  email: "webb.henderson@gmail.com"
  facebook: emerywebster  # eg. daattali
  github: emerywebster    # eg. daattali
  twitter: emerywebster   # eg. daattali
  linkedin: in/emerywebster  # eg. "pub/dean-attali/8/946/143"
  # stackoverflow: emerywebster  # eg. "3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: true
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "emerywebster.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: emerywebster

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-8462524-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Denver"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
  
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
